mail:
  google:
    host: smtp.gmail.com
    port: 587
    username: swc05161@gmail.com
    password: eaalxbwhfzyuxdan
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

spring:
  properties:
    hibernate:
      default_batch_fetch_size: 100
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  redis:
    host: localhost
    port: 6379


  mvc:
    contentnegotiation:
      defaultContentType: application/json

server:
  client-uri: http://localhost:5173

  error:
    path: /error
    whitelabel:
      enabled: false


logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.config: DEBUG
